/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author denis
 */
public class AnalysisViewNetbeans extends javax.swing.JPanel {
    
   

    /**
     * Creates new form AnalysisViewNetbeans
     */
    public AnalysisViewNetbeans() {
        initComponents();
        textArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        label2 = new javax.swing.JLabel();
        continuarButton2 = new javax.swing.JButton();
        sairButton4 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();

        textArea1.setColumns(20);
        textArea1.setRows(5);
        scrollPane1.setViewportView(textArea1);

        label2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        label2.setText("Deseja Continuar?");

        continuarButton2.setText("Sim");

        sairButton4.setText("Não");

        label1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        label1.setText("Análise do Algoritmo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(label2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(continuarButton2)
                        .addGap(32, 32, 32)
                        .addComponent(sairButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1)
                .addGap(2, 2, 2)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuarButton2)
                    .addComponent(sairButton4))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextArea getTextArea1() {
        return textArea1;
    }

    public JButton getContinuarButton2() {
        return continuarButton2;
    }

    public JButton getSairButton4() {
        return sairButton4;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarButton2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JButton sairButton4;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JTextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
