/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author denis
 */
public class ExitViewNetbeans extends javax.swing.JPanel {

    /**
     * Creates new form ExitViewNetbeans
     */
    public ExitViewNetbeans() {
        initComponents();
        String nomes = "Denis Alves<br>" +
                "Ulisses Aguiar";
        nomesLabel.setText("<html>" + nomes + "</html>");

        String curso = "BSI | Segundo Semestre<br>" +
                "2025";
        cursoLabel.setText("<html>" + curso + "</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        nomesLabel = new javax.swing.JLabel();
        cursoLabel = new javax.swing.JLabel();

        label1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        label1.setText("Obrigado por usar nosso programa :)");

        nomesLabel.setText("jLabel2");

        cursoLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(nomesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cursoLabel)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(label1)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(label1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomesLabel)
                    .addComponent(cursoLabel))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cursoLabel;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel nomesLabel;
    // End of variables declaration//GEN-END:variables
}
