/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author denis
 */
public class QuantityInputViewNetbeans extends javax.swing.JPanel {

    /**
     * Creates new form QuantityInputViewNetbeans
     */
    public QuantityInputViewNetbeans() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digiteQuantidadeLabel = new javax.swing.JLabel();
        textField1 = new javax.swing.JTextField();
        analisarButton = new javax.swing.JButton();
        sairButton2 = new javax.swing.JButton();

        digiteQuantidadeLabel.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        digiteQuantidadeLabel.setText("Digite a quantidade de números para serem ordenados");

        analisarButton.setText("Analisar");

        sairButton2.setText("Sair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(digiteQuantidadeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(sairButton2))
                            .addComponent(analisarButton)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(digiteQuantidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analisarButton)
                    .addComponent(sairButton2))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

public JTextField getTextField1() {
        return textField1;
    }

    public JLabel getDigiteQuantidadeLabel() {
        return digiteQuantidadeLabel;
    }

    public JButton getAnalisarButton() {
        return analisarButton;
    }

    public JButton getSairButton2() {
        return sairButton2;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analisarButton;
    private javax.swing.JLabel digiteQuantidadeLabel;
    private javax.swing.JButton sairButton2;
    private javax.swing.JTextField textField1;
    // End of variables declaration//GEN-END:variables
}
