
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author denis
 */
public class SelectViewNetbeans extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanelSelect
     */
    public SelectViewNetbeans() {
        initComponents();
        dropDown1.addItem("Bubble Sort");
        dropDown1.addItem("Selection Sort");
        dropDown1.addItem("Insertion Sort");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        dropDown1 = new javax.swing.JComboBox<>();
        continuarButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        label1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        label1.setText("Escolha um algoritmo de ordenação");

        dropDown1.setMaximumRowCount(3);
        dropDown1.setMaximumSize(null);
        dropDown1.setMinimumSize(null);
        dropDown1.setPreferredSize(null);

        continuarButton.setText("Continuar");
        continuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(continuarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(sairButton)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dropDown1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(dropDown1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuarButton)
                    .addComponent(sairButton))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continuarButtonActionPerformed

    public JButton getContinuarButton() {
        return continuarButton;
    }

    public JComboBox getDropDown1() {
        return dropDown1;
    }

    public JLabel getLabel1() {
        return label1;
    }

    public JButton getSairButton() {
        return sairButton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarButton;
    private javax.swing.JComboBox<String> dropDown1;
    private javax.swing.JLabel label1;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
